#=================================================================================
# \u57FA\u7840 \u914D\u7F6E
#==================================================================================
go:
  applicationName: chaos-component-service

#=================================================================================
# spring \u914D\u7F6E
#==================================================================================
spring:
  profiles:
    active: local
  application:
     name: chaos-component-service
#  redis:
#     host: 61.14.255.57
#     port: 6378

#=================================================================================
# \u65E5\u5FD7 \u914D\u7F6E
#==================================================================================
#logging:
#  path: /data/deploy/boss_service/logs
#  level:
#   com.chaos.boss.dao : debug
logging:
  level:
   com.chaos.boss.dao : debug

#=================================================================================
# oracle \u914D\u7F6E
#==================================================================================
app:
    db:
        dialect: oracle
        initialSize: 1
        maxActive: 200
        password: cash_settle_2018
        url: jdbc:oracle:thin:@//61.14.255.57:1521/sitpay1
        username: cash_settle

#=================================================================================
# dubbo \u914D\u7F6E
#==================================================================================
dubbo:
    protocol:
      port: -1
    application:
        name: chaos-component-service
    consumer:
        group: chaos
    provider:
        group: chaos
        version: 1.0.0
    registry:
        address: zookeeper://61.14.255.57:2184
        id: chaos
    monitor:
        protocol: dubbo
#=================================================================================
# \u4E1A\u52A1 \u914D\u7F6E
#==================================================================================
#vipay:
#    dubbo:
#        registry: zookeeper://61.14.255.57:2184

#=================================================================================
# mq \u914D\u7F6E
#==================================================================================
rocketmq:
  name-server: 61.14.255.57:9878
  producer:
    group: chaos-component-service
  consumer:
    group: chaos-component-service
    maxReconsumeTimes: 10
check:
    rocketmq:
        consumerMonitorLogTopic: CHAOS_MONITOR_MESSAGE_LOG_TOPIC




